@startuml cesar
skinparam groupInheritance 2

class CaesarCipher{
  +static string encrypt(string text, int clave)
  +static string desencrypt(string textEncrypted, int clave)
}

class CaesarAttack{
  -char[2] : createRandomKey()
  +string[] getTextsProbable(int limit)
}

' Una clase que se encarga de las operaciones sobre archivos, en este caso sólo escritura y lectura
class FileService {
  + static string readFile(string path)
  + static void writeTxt(string path, string text)
}

abstract WordsShorts{
  + static PRONOUNS : string[]
  + static VERBS_AUX : string[]
  + static ARTICLES : string[]
  + static LETTERS_MORE_USE : char[]
}

WordsShorts <|-- CaesarAttack
FileService <.. CaesarCipher
FileService <.. CaesarAttack
CaesarCipher <.. CaesarAttack
@enduml